version: "3.8"
services:
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    environment:
      MARIADB_USER: user
      MARIADB_ROOT_PASSWORD: mypassword
      MARIADB_PASSWORD: mypassword
      MARIAGB_DATABASE: testdb
    volumes:
      - persistent:/var/lib/mysql
    ports:
      - '3306:3306'
  phymyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8802:80'
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: mypassword
    links:
      - db
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./php/src:/var/www/html/
    links:
      - db
    ports:
      - '8080:80'

volumes:
  persistent:
